version: '3.8'

services:
  redis:
    image: redis:6-alpine
    container_name: redis-refresh
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: 615299734340.dkr.ecr.ap-northeast-2.amazonaws.com/zarinatta-domain:latest
    container_name: zarinatta-app
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

volumes:
  redis-data:
