package com.zarinatta.zarinattaserver.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Station {
    // 가
    GANAM("가남"),
    GAPYEONG("가평"),
    GAKGYE("각계"),
    GAMGOK_JANGHOWON("감곡장호원"),
    GANGGYEONG("강경"),
    GANGGU("강구"),
    GANGNEUNG("강릉"),
    GANGCHON("강촌"),
    GAEPO("개포"),
    GEONCHEON("건천"),
    GYEONGSAN("경산"),
    GYEONGJU("경주"),
    GYERYONG("계룡"),
    GOHAN("고한"),
    GOKSEONG("곡성"),
    GONGJU("공주"),
    GWANGMYEONG("광명"),
    GWANGYANG("광양"),
    GWANGJU("광주"),
    GWANGJU_SONGJEONG("광주송정"),
    GWANGCHEON("광천"),
    GURYEGU("구례구"),
    GUMI("구미"),
    GUPO("구포"),
    GUNBUK("군북"),
    GUNSAN("군산"),
    GEUKRAKGANG("극락강"),
    GIJANG("기장"),
    GIMJE("김제"),
    GIMCHEON("김천"),
    GIMCHEON_GUMI("김천구미"),


    // 나
    NAJEON("나전"),
    NAJU("나주"),
    NAMSEONGHYUN("남성현"),
    NAMWON("남원"),
    NAMCHANG("남창"),
    NAMCHUNCHEON("남춘천"),
    NONGSAN("논산"),
    NEUNGJU("능주"),

    // 다
    DASI("다시"),
    DANYANG("단양"),
    DAEGU("대구"),
    DEAYA("대야"),
    DAEJEON("대전"),
    DAECHEON("대천"),
    DEOKSO("덕소"),
    DEOKHA("덕하"),
    DOGYE("도계"),
    DOGO_ONCHEON("도고온천"),
    DORASAN("도라산"),
    DONGDAEGU("동대구"),
    DONGBAEKSAN("동백산"),
    DONGTAN("동탄"),
    DONGHAE("동해"),
    DONGHWA("동화"),
    DONNAE("둔내"),
    DEUKRANG("득량"),

    // 마
    MASAN("마산"),
    MASEOK("마석"),
    MANJONG("만종"),
    MAEGOK("매곡"),
    MYEONGBONG("명봉"),
    MOKPO("목포"),
    MONGTAN("몽탄"),
    MUAN("무안"),
    MOKHO("묵호"),
    MUNSAN("문산"),
    MULGEUM("물금"),
    MINDEUNGSAN("민둥산"),
    MIRYANG("밀양"),

    // 반
    BANGO("반곡"),
    BANSEONG("반성"),
    BAEKYANGLI("백양리"),
    BAEKYANGSA("백양사"),
    BEOLGYO("벌교"),
    BEOLEOGOK("벌어곡"),
    BOSEONG("보성"),
    BONGYANG("봉양"),
    BONGHWA("봉화"),
    BUGANG("부강"),
    BUBAL("부발"),
    BUSAN("부산"),
    BUJEON("부전"),
    BUGYEONGCHEON("북영천"),
    BUKULSAN("북울산"),
    BUKCHEON("북천"),
    BUNCHEON("분천"),
    BULGUKSA("불국사"),
    BIDONG("비동"),

    // 사
    SAREUNG("사릉"),
    SABOK("사북"),
    SASANG("사상"),
    SAMRANGJIN("삼랑진"),
    SAMRE("삼례"),
    SAMSAN("삼산"),
    SAMTAN("삼탄"),
    SAPGYO("삽교"),
    SANGDONG("상동"),
    SANGBONG("상봉"),
    SANGJU("상주"),
    SEO_GYEONGJU("서경주"),
    SEO_GWANGJU("서광주"),
    SEO_DAEGU("서대구"),
    SEO_DAEJEON("서대전"),
    SEO_UL("서울"),
    SEOWONJU("서원주"),
    SEOJEONGRI("서정리"),
    SEOCHUN("서천"),
    SEOKBUL("석불"),
    SEOKPO("석포"),
    SEONPYEONG("선평"),
    SEONGHWAN("성환"),
    SENTEM("센텀"),
    SUSHE("수서"),
    SUWON("수원"),
    SUNCHEON("순천"),
    SEUNGBU("승부"),
    SINGI("신기"),
    SINNONG("신녕"),
    SINDONG("신동"),
    SINRAE_ON("신례원"),
    SINRIM("신림"),
    SINTANJIN("신탄진"),
    SINTAE_IN("신태인"),
    SINHAE_UNDAE("신해운대"),
    SIMCHEON("심천"),
    SSANGRYONG("쌍룡"),

    // 아
    ASAN("아산"),
    AOURAJI("아우라지"),
    AHWA("아화"),
    ANGANG("안강"),
    ANDONG("안동"),
    ANYANG("안양"),
    ANGSEONG_ONCHEON("양성온천"),
    YAKMOK("약목"),
    YANGDONG("양동"),
    YANGWON("양원"),
    YANGPYUNG("양평"),
    YEOSU_EXPO("여수EXPO"),
    YEOJEON("여전"),
    YEONSAN("연산"),
    YEONGDEOK("영덕"),
    YEONGDONG("영동"),
    YEONGDEUNGPO("영등포"),
    YEONGWOL("영월"),
    YEONGJU("영주"),
    YEONGCHEON("영천"),
    YEDANG("예당"),
    YEMI("예미"),
    YESAN("예산"),
    YECHEON("예천"),
    O_GEUNJANG("오근장"),
    OSAN("오산"),
    OSUNG("오송"),
    OSU("오수"),
    OKSAN("옥산"),
    OKSU("옥수"),
    OKCHEON("옥천"),
    O_GO_ONCHEON("온양온천"),
    WANSAN("완산"),
    WANGSIMNI("왕십리"),
    WAEPYEONG("왜관"),
    YONGGUNG("용궁"),
    YONGMUN("용문"),
    YONGSAN("용산"),
    UNCHEON("운천"),
    ULSAN_TONGDOSA("울산(통도사)"),
    UNGCHEON("웅천"),
    WONDEONG("원동"),
    WONJU("원주"),
    WOLPO("월포"),
    EUMSEONG("음성"),
    UISUNG("의성"),
    IYANG("이양"),
    IWON("이원"),
    IKSAN("익산"),
    INCHEON_GONGHANG_T1("인천공항T1"),
    INCHEON_GONGHANG_T2("인천공항T2"),
    ILRO("일로"),
    ILSIN("일신"),
    IMGI("임기"),
    IMSANRI("임성리"),
    IMSIL("임실"),
    IMJINGANG("임진강"),

    // 장
    JANGSA("장사"),
    JANGSEONG("장성"),
    JANGHANG("장항"),
    JEON_UI("전의"),
    JEONJU("전주"),
    JEMCHON("점촌"),
    JEONGDONGJIN("정동진"),
    JEONGSEON("정선"),
    JEONGUP("정읍"),
    JE_CHUN("제천"),
    JOSUNG("조성"),
    JOSIWON("조치원"),
    JWA_CHON("좌천"),
    JU_DEUK("주덕"),
    JUNG_LI("중리"),
    JEUNG_PYUNG("증평"),
    JITAN("지탄"),
    JI_PYUNG("지평"),
    JIN_LAE("진례"),
    JIN_BU("진부(오대산)"),
    JIN_SANG("진상"),
    JIN_YEONG("진영"),
    JIN_JU("진주"),

    // 창
    CHANGWON("창원"),
    CHANGWON_JOONGANG("창원중앙"),
    CHEONAN("천안"),
    CHEONAN_ASAN("천안아산"),
    CHEOL_AM("철암"),
    CHEONDO("청도"),
    CHEONGLYANG_RI("청량리"),
    CHEONGRI("청리"),
    CHEONGSO("청소"),
    CHEONGJU("청주"),
    CHEONGJU_GONGHANG("청주공항"),
    CHEONGPYUNG("청평"),
    CHUPUNG_REUNG("추풍령"),
    CHUNYANG("춘양"),
    CHUNCHEON("춘천"),
    CUNGJU("충주"),

    // 탑
    TAPRI("탑리"),
    TAEBAEK("태백"),
    TAEHWA_GANG("태화강"),
    TOEGE_WON("퇴계원"),

    //파
    PANGYO_GYEONGGI("판교(경기)"),
    PANGYO_CHUNGNAM("판교(충남)"),
    PYEONGNAE_HOPEONG("평내호평"),
    PYEONGCHANG("평창"),
    PYEONGTAEK("평택"),
    PYEONGTAEK_JIJAE("평택지제"),
    POHANG("포항"),
    PUNGGI("풍기"),

    //하
    HADONG("하동"),
    HAYANG("하양"),
    HANRIMJEONG("한림정"),
    HAMAN("함안"),
    HAMYEOL("함열"),
    HAMCHANG("함창"),
    HAMPYEONG("함평"),
    HAENGSIN("행신"),
    HYONDDONG("현동"),
    HOGYE("호계"),
    HONGSEONG("홍성"),
    HWAMYEONG("화명"),
    HWABON("화본"),
    HWAJUN("화순"),
    HWANGGAN("황간"),
    HWANGSEONG("횡성"),
    HWANJEON("황전"),
    HYOJEON("효전"),
    HWIBANGSA("희방사");


    private final String name;
}
